title: The Fifth Elephant
subtitle: "India's most renowned data science community and conference"
description: "Indiaâ€™s most renowned data science conference. Discuss the most cutting edge developments in the fields of machine learning, data science and technology that power data collection and analysis."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fifthelephant.in" # the base hostname & protocol for your site, e.g. http://example.com
colors:
  primary: "#498f94"
  accent: "#EC6015"
ga_tracking_code: UA-19123154-20
icons:
  touch:
  - src: "images/touch/fifthelephant-icon-192.png"
    sizes: "192x192"
    type: "image/png"
id: fifthelephant
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .git
  - .sass_cache
  - node_modules
  - _site
  - tests
  - vendor
  - .DS_Store
  - configs
  - deploy
  - requirements.txt
  - README.md

destination: _site/fifthelephant

sass_dir: _sass

liquid:
  error_mode: strict

collections:
  fifthelephant_events:
    type: event
    output: true
    permalink: /:path/
