title: JSFoo
subtitle: "A community and conference on JavaScript"
description: "A community and conference on JavaScript"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jsfoo.in" # the base hostname & protocol for your site, e.g. http://example.com
colors:
  primary: "#549EAF"
  accent: "#FAA51A"
ga_tracking_code: UA-19123154-19
icons:
  touch:
  - src: "images/touch/jsfoo-icon-300.png"
    sizes: "300x300"
    type: "image/png"
id: jsfoo
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .git
  - .sass_cache
  - node_modules
  - _site
  - tests
  - vendor
  - .DS_Store
  - configs
  - deploy
  - requirements.txt
  - README.md

destination: _site/jsfoo

sass_dir: _sass

liquid:
  error_mode: strict

collections:
  jsfoo_events:
    type: event
    output: true
    permalink: /:path/
